"""empty message

Revision ID: 994a525c4abf
Revises: 2ddd3f7fc2dd
Create Date: 2024-06-12 14:54:25.388367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994a525c4abf'
down_revision = '2ddd3f7fc2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_open', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('days_open')

    # ### end Alembic commands ###
